"""empty message

Revision ID: 1710b2fdda00
Revises: 391d03458234
Create Date: 2022-09-02 16:42:54.176257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1710b2fdda00'
down_revision = '391d03458234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'money')
    # ### end Alembic commands ###
