"""empty message

Revision ID: 56ef2c90e7f5
Revises: 6c5ac925e240
Create Date: 2022-09-06 11:29:54.098367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ef2c90e7f5'
down_revision = '6c5ac925e240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_slip', 'oddsTie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_slip', sa.Column('oddsTie', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
