"""empty message

Revision ID: 57307cf54e31
Revises: 75cef87ed666
Create Date: 2022-09-15 10:20:04.503094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57307cf54e31'
down_revision = '75cef87ed666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_slip', sa.Column('odds', sa.Integer(), nullable=True))
    op.drop_column('bet_slip', 'odds1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_slip', sa.Column('odds1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bet_slip', 'odds')
    # ### end Alembic commands ###
