"""empty message

Revision ID: 6c5ac925e240
Revises: 1710b2fdda00
Create Date: 2022-09-02 16:45:06.090987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5ac925e240'
down_revision = '1710b2fdda00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userBets', sa.Column('money', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userBets', 'money')
    # ### end Alembic commands ###
