"""empty message

Revision ID: 75cef87ed666
Revises: 25a686d8aded
Create Date: 2022-09-15 10:01:15.611906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cef87ed666'
down_revision = '25a686d8aded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_slip', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bet_slip', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet_slip', type_='foreignkey')
    op.drop_column('bet_slip', 'user_id')
    # ### end Alembic commands ###
